// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.17.3
// source: canoto.go

package canoto

import (
	"io"
	"reflect"
	"sync/atomic"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = VersionCompatibility - 0
	_ uint = 0 - VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__Spec__Name   = 1
	canoto__Spec__Fields = 2

	canoto__Spec__Name__tag   = "\x0a" // canoto.Tag(canoto__Spec__Name, canoto.Len)
	canoto__Spec__Fields__tag = "\x12" // canoto.Tag(canoto__Spec__Fields, canoto.Len)
)

type canotoData_Spec struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*Spec) CanotoSpec(types ...reflect.Type) *Spec {
	types = append(types, reflect.TypeOf(Spec{}))
	var zero Spec
	s := &Spec{
		Name: "Spec",
		Fields: []FieldType{
			{
				FieldNumber: canoto__Spec__Name,
				Name:        "Name",
				OneOf:       "",
				TypeString:  true,
			},
			FieldTypeFromField(
				/*type inference:*/ (MakeEntryNilPointer(zero.Fields)),
				/*FieldNumber:   */ canoto__Spec__Fields,
				/*Name:          */ "Fields",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*Spec) MakeCanoto() *Spec {
	return new(Spec)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *Spec) UnmarshalCanoto(bytes []byte) error {
	r := Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *Spec) UnmarshalCanotoFrom(r Reader) error {
	// Zero the struct before unmarshaling.
	*c = Spec{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for HasNext(&r) {
		field, wireType, err := ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return ErrInvalidFieldOrder
		}

		switch field {
		case canoto__Spec__Name:
			if wireType != Len {
				return ErrUnexpectedWireType
			}

			if err := ReadString(&r, &c.Name); err != nil {
				return err
			}
			if len(c.Name) == 0 {
				return ErrZeroValue
			}
		case canoto__Spec__Fields:
			if wireType != Len {
				return ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := CountBytes(r.B, canoto__Spec__Fields__tag)
			if err != nil {
				return err
			}

			c.Fields = MakeSlice(c.Fields, countMinus1+1)
			field := c.Fields
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canoto__Spec__Fields__tag):]
				r.Unsafe = true
				if err := ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				if len(msgBytes) == 0 {
					continue
				}
				r.Unsafe = originalUnsafe

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		default:
			return ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Spec) ValidCanoto() bool {
	if c == nil {
		return true
	}
	if !ValidString(c.Name) {
		return false
	}
	{
		field := c.Fields
		for i := range field {
			if !(&field[i]).ValidCanoto() {
				return false
			}
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *Spec) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if len(c.Name) != 0 {
		size += uint64(len(canoto__Spec__Name__tag)) + SizeBytes(c.Name)
	}
	{
		field := c.Fields
		for i := range field {
			(&field[i]).CalculateCanotoCache()
			fieldSize := (&field[i]).CachedCanotoSize()
			size += uint64(len(canoto__Spec__Fields__tag)) + SizeUint(fieldSize) + fieldSize
		}
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Spec) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Spec) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [Writer] and returns the
// resulting [Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Spec) MarshalCanotoInto(w Writer) Writer {
	if c == nil {
		return w
	}
	if len(c.Name) != 0 {
		Append(&w, canoto__Spec__Name__tag)
		AppendBytes(&w, c.Name)
	}
	{
		field := c.Fields
		for i := range field {
			Append(&w, canoto__Spec__Fields__tag)
			AppendUint(&w, (&field[i]).CachedCanotoSize())
			w = (&field[i]).MarshalCanotoInto(w)
		}
	}
	return w
}

const (
	canoto__FieldType__FieldNumber    = 1
	canoto__FieldType__Name           = 2
	canoto__FieldType__FixedLength    = 3
	canoto__FieldType__Repeated       = 4
	canoto__FieldType__OneOf          = 5
	canoto__FieldType__TypeInt        = 6
	canoto__FieldType__TypeUint       = 7
	canoto__FieldType__TypeFixedInt   = 8
	canoto__FieldType__TypeFixedUint  = 9
	canoto__FieldType__TypeBool       = 10
	canoto__FieldType__TypeString     = 11
	canoto__FieldType__TypeBytes      = 12
	canoto__FieldType__TypeFixedBytes = 13
	canoto__FieldType__TypeRecursive  = 14
	canoto__FieldType__TypeMessage    = 15

	canoto__FieldType__FieldNumber__tag    = "\x08" // canoto.Tag(canoto__FieldType__FieldNumber, canoto.Varint)
	canoto__FieldType__Name__tag           = "\x12" // canoto.Tag(canoto__FieldType__Name, canoto.Len)
	canoto__FieldType__FixedLength__tag    = "\x18" // canoto.Tag(canoto__FieldType__FixedLength, canoto.Varint)
	canoto__FieldType__Repeated__tag       = "\x20" // canoto.Tag(canoto__FieldType__Repeated, canoto.Varint)
	canoto__FieldType__OneOf__tag          = "\x2a" // canoto.Tag(canoto__FieldType__OneOf, canoto.Len)
	canoto__FieldType__TypeInt__tag        = "\x30" // canoto.Tag(canoto__FieldType__TypeInt, canoto.Varint)
	canoto__FieldType__TypeUint__tag       = "\x38" // canoto.Tag(canoto__FieldType__TypeUint, canoto.Varint)
	canoto__FieldType__TypeFixedInt__tag   = "\x40" // canoto.Tag(canoto__FieldType__TypeFixedInt, canoto.Varint)
	canoto__FieldType__TypeFixedUint__tag  = "\x48" // canoto.Tag(canoto__FieldType__TypeFixedUint, canoto.Varint)
	canoto__FieldType__TypeBool__tag       = "\x50" // canoto.Tag(canoto__FieldType__TypeBool, canoto.Varint)
	canoto__FieldType__TypeString__tag     = "\x58" // canoto.Tag(canoto__FieldType__TypeString, canoto.Varint)
	canoto__FieldType__TypeBytes__tag      = "\x60" // canoto.Tag(canoto__FieldType__TypeBytes, canoto.Varint)
	canoto__FieldType__TypeFixedBytes__tag = "\x68" // canoto.Tag(canoto__FieldType__TypeFixedBytes, canoto.Varint)
	canoto__FieldType__TypeRecursive__tag  = "\x70" // canoto.Tag(canoto__FieldType__TypeRecursive, canoto.Varint)
	canoto__FieldType__TypeMessage__tag    = "\x7a" // canoto.Tag(canoto__FieldType__TypeMessage, canoto.Len)
)

type canotoData_FieldType struct {
	size uint64

	TypeOneOf uint32
}

// CanotoSpec returns the specification of this canoto message.
func (*FieldType) CanotoSpec(types ...reflect.Type) *Spec {
	types = append(types, reflect.TypeOf(FieldType{}))
	var zero FieldType
	s := &Spec{
		Name: "FieldType",
		Fields: []FieldType{
			{
				FieldNumber: canoto__FieldType__FieldNumber,
				Name:        "FieldNumber",
				OneOf:       "",
				TypeUint:    SizeOf(zero.FieldNumber),
			},
			{
				FieldNumber: canoto__FieldType__Name,
				Name:        "Name",
				OneOf:       "",
				TypeString:  true,
			},
			{
				FieldNumber: canoto__FieldType__FixedLength,
				Name:        "FixedLength",
				OneOf:       "",
				TypeUint:    SizeOf(zero.FixedLength),
			},
			{
				FieldNumber: canoto__FieldType__Repeated,
				Name:        "Repeated",
				OneOf:       "",
				TypeBool:    true,
			},
			{
				FieldNumber: canoto__FieldType__OneOf,
				Name:        "OneOf",
				OneOf:       "",
				TypeString:  true,
			},
			{
				FieldNumber: canoto__FieldType__TypeInt,
				Name:        "TypeInt",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeInt),
			},
			{
				FieldNumber: canoto__FieldType__TypeUint,
				Name:        "TypeUint",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeUint),
			},
			{
				FieldNumber: canoto__FieldType__TypeFixedInt,
				Name:        "TypeFixedInt",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeFixedInt),
			},
			{
				FieldNumber: canoto__FieldType__TypeFixedUint,
				Name:        "TypeFixedUint",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeFixedUint),
			},
			{
				FieldNumber: canoto__FieldType__TypeBool,
				Name:        "TypeBool",
				OneOf:       "Type",
				TypeBool:    true,
			},
			{
				FieldNumber: canoto__FieldType__TypeString,
				Name:        "TypeString",
				OneOf:       "Type",
				TypeBool:    true,
			},
			{
				FieldNumber: canoto__FieldType__TypeBytes,
				Name:        "TypeBytes",
				OneOf:       "Type",
				TypeBool:    true,
			},
			{
				FieldNumber: canoto__FieldType__TypeFixedBytes,
				Name:        "TypeFixedBytes",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeFixedBytes),
			},
			{
				FieldNumber: canoto__FieldType__TypeRecursive,
				Name:        "TypeRecursive",
				OneOf:       "Type",
				TypeUint:    SizeOf(zero.TypeRecursive),
			},
			FieldTypeFromField(
				/*type inference:*/ (zero.TypeMessage),
				/*FieldNumber:   */ canoto__FieldType__TypeMessage,
				/*Name:          */ "TypeMessage",
				/*FixedLength:   */ 0,
				/*Repeated:      */ false,
				/*OneOf:         */ "Type",
				/*types:         */ types,
			),
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*FieldType) MakeCanoto() *FieldType {
	return new(FieldType)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *FieldType) UnmarshalCanoto(bytes []byte) error {
	r := Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *FieldType) UnmarshalCanotoFrom(r Reader) error {
	// Zero the struct before unmarshaling.
	*c = FieldType{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for HasNext(&r) {
		field, wireType, err := ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return ErrInvalidFieldOrder
		}

		switch field {
		case canoto__FieldType__FieldNumber:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}

			if err := ReadUint(&r, &c.FieldNumber); err != nil {
				return err
			}
			if IsZero(c.FieldNumber) {
				return ErrZeroValue
			}
		case canoto__FieldType__Name:
			if wireType != Len {
				return ErrUnexpectedWireType
			}

			if err := ReadString(&r, &c.Name); err != nil {
				return err
			}
			if len(c.Name) == 0 {
				return ErrZeroValue
			}
		case canoto__FieldType__FixedLength:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}

			if err := ReadUint(&r, &c.FixedLength); err != nil {
				return err
			}
			if IsZero(c.FixedLength) {
				return ErrZeroValue
			}
		case canoto__FieldType__Repeated:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}

			if err := ReadBool(&r, &c.Repeated); err != nil {
				return err
			}
			if IsZero(c.Repeated) {
				return ErrZeroValue
			}
		case canoto__FieldType__OneOf:
			if wireType != Len {
				return ErrUnexpectedWireType
			}

			if err := ReadString(&r, &c.OneOf); err != nil {
				return err
			}
			if len(c.OneOf) == 0 {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeInt:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 6) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeInt); err != nil {
				return err
			}
			if IsZero(c.TypeInt) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeUint:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 7) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeUint); err != nil {
				return err
			}
			if IsZero(c.TypeUint) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeFixedInt:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 8) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeFixedInt); err != nil {
				return err
			}
			if IsZero(c.TypeFixedInt) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeFixedUint:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 9) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeFixedUint); err != nil {
				return err
			}
			if IsZero(c.TypeFixedUint) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeBool:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 10) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadBool(&r, &c.TypeBool); err != nil {
				return err
			}
			if IsZero(c.TypeBool) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeString:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 11) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadBool(&r, &c.TypeString); err != nil {
				return err
			}
			if IsZero(c.TypeString) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeBytes:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 12) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadBool(&r, &c.TypeBytes); err != nil {
				return err
			}
			if IsZero(c.TypeBytes) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeFixedBytes:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 13) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeFixedBytes); err != nil {
				return err
			}
			if IsZero(c.TypeFixedBytes) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeRecursive:
			if wireType != Varint {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 14) != 0 {
				return ErrDuplicateOneOf
			}

			if err := ReadUint(&r, &c.TypeRecursive); err != nil {
				return err
			}
			if IsZero(c.TypeRecursive) {
				return ErrZeroValue
			}
		case canoto__FieldType__TypeMessage:
			if wireType != Len {
				return ErrUnexpectedWireType
			}
			if atomic.SwapUint32(&c.canotoData.TypeOneOf, 15) != 0 {
				return ErrDuplicateOneOf
			}

			// Read the bytes for the field.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			if len(msgBytes) == 0 {
				return ErrZeroValue
			}
			r.Unsafe = originalUnsafe

			// Unmarshal the field from the bytes.
			remainingBytes := r.B
			r.B = msgBytes
			c.TypeMessage = MakePointer(c.TypeMessage)
			if err := (c.TypeMessage).UnmarshalCanotoFrom(r); err != nil {
				return err
			}
			r.B = remainingBytes
		default:
			return ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *FieldType) ValidCanoto() bool {
	if c == nil {
		return true
	}
	var TypeOneOf uint32
	if !IsZero(c.TypeInt) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeInt
	}
	if !IsZero(c.TypeUint) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeUint
	}
	if !IsZero(c.TypeFixedInt) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeFixedInt
	}
	if !IsZero(c.TypeFixedUint) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeFixedUint
	}
	if !IsZero(c.TypeBool) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeBool
	}
	if !IsZero(c.TypeString) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeString
	}
	if !IsZero(c.TypeBytes) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeBytes
	}
	if !IsZero(c.TypeFixedBytes) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeFixedBytes
	}
	if !IsZero(c.TypeRecursive) {
		if TypeOneOf != 0 {
			return false
		}
		TypeOneOf = canoto__FieldType__TypeRecursive
	}
	if c.TypeMessage != nil {
		(c.TypeMessage).CalculateCanotoCache()
		if (c.TypeMessage).CachedCanotoSize() != 0 {
			if TypeOneOf != 0 {
				return false
			}
			TypeOneOf = canoto__FieldType__TypeMessage
		}
	}
	if !ValidString(c.Name) {
		return false
	}
	if !ValidString(c.OneOf) {
		return false
	}
	if c.TypeMessage != nil && !(c.TypeMessage).ValidCanoto() {
		return false
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *FieldType) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	var TypeOneOf uint32
	if !IsZero(c.FieldNumber) {
		size += uint64(len(canoto__FieldType__FieldNumber__tag)) + SizeUint(c.FieldNumber)
	}
	if len(c.Name) != 0 {
		size += uint64(len(canoto__FieldType__Name__tag)) + SizeBytes(c.Name)
	}
	if !IsZero(c.FixedLength) {
		size += uint64(len(canoto__FieldType__FixedLength__tag)) + SizeUint(c.FixedLength)
	}
	if !IsZero(c.Repeated) {
		size += uint64(len(canoto__FieldType__Repeated__tag)) + SizeBool
	}
	if len(c.OneOf) != 0 {
		size += uint64(len(canoto__FieldType__OneOf__tag)) + SizeBytes(c.OneOf)
	}
	if !IsZero(c.TypeInt) {
		size += uint64(len(canoto__FieldType__TypeInt__tag)) + SizeUint(c.TypeInt)
		TypeOneOf = 6
	}
	if !IsZero(c.TypeUint) {
		size += uint64(len(canoto__FieldType__TypeUint__tag)) + SizeUint(c.TypeUint)
		TypeOneOf = 7
	}
	if !IsZero(c.TypeFixedInt) {
		size += uint64(len(canoto__FieldType__TypeFixedInt__tag)) + SizeUint(c.TypeFixedInt)
		TypeOneOf = 8
	}
	if !IsZero(c.TypeFixedUint) {
		size += uint64(len(canoto__FieldType__TypeFixedUint__tag)) + SizeUint(c.TypeFixedUint)
		TypeOneOf = 9
	}
	if !IsZero(c.TypeBool) {
		size += uint64(len(canoto__FieldType__TypeBool__tag)) + SizeBool
		TypeOneOf = 10
	}
	if !IsZero(c.TypeString) {
		size += uint64(len(canoto__FieldType__TypeString__tag)) + SizeBool
		TypeOneOf = 11
	}
	if !IsZero(c.TypeBytes) {
		size += uint64(len(canoto__FieldType__TypeBytes__tag)) + SizeBool
		TypeOneOf = 12
	}
	if !IsZero(c.TypeFixedBytes) {
		size += uint64(len(canoto__FieldType__TypeFixedBytes__tag)) + SizeUint(c.TypeFixedBytes)
		TypeOneOf = 13
	}
	if !IsZero(c.TypeRecursive) {
		size += uint64(len(canoto__FieldType__TypeRecursive__tag)) + SizeUint(c.TypeRecursive)
		TypeOneOf = 14
	}
	if c.TypeMessage != nil {
		(c.TypeMessage).CalculateCanotoCache()
		if fieldSize := (c.TypeMessage).CachedCanotoSize(); fieldSize != 0 {
			size += uint64(len(canoto__FieldType__TypeMessage__tag)) + SizeUint(fieldSize) + fieldSize
			TypeOneOf = 15
		}
	}
	atomic.StoreUint64(&c.canotoData.size, size)
	atomic.StoreUint32(&c.canotoData.TypeOneOf, TypeOneOf)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *FieldType) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// CachedWhichOneOfType returns the previously calculated field number used
// to represent Type.
//
// This field is cached by UnmarshalCanoto, UnmarshalCanotoFrom, and
// CalculateCanotoCache.
//
// If the field has not yet been cached, it will return 0.
//
// If the struct has been modified since the field was last cached, the returned
// field number may be incorrect.
func (c *FieldType) CachedWhichOneOfType() uint32 {
	return atomic.LoadUint32(&c.canotoData.TypeOneOf)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *FieldType) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [Writer] and returns the
// resulting [Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *FieldType) MarshalCanotoInto(w Writer) Writer {
	if c == nil {
		return w
	}
	if !IsZero(c.FieldNumber) {
		Append(&w, canoto__FieldType__FieldNumber__tag)
		AppendUint(&w, c.FieldNumber)
	}
	if len(c.Name) != 0 {
		Append(&w, canoto__FieldType__Name__tag)
		AppendBytes(&w, c.Name)
	}
	if !IsZero(c.FixedLength) {
		Append(&w, canoto__FieldType__FixedLength__tag)
		AppendUint(&w, c.FixedLength)
	}
	if !IsZero(c.Repeated) {
		Append(&w, canoto__FieldType__Repeated__tag)
		AppendBool(&w, true)
	}
	if len(c.OneOf) != 0 {
		Append(&w, canoto__FieldType__OneOf__tag)
		AppendBytes(&w, c.OneOf)
	}
	cachedWhichOneOfType := atomic.LoadUint32(&c.canotoData.TypeOneOf)
	switch cachedWhichOneOfType {
	case canoto__FieldType__TypeInt:
		Append(&w, canoto__FieldType__TypeInt__tag)
		AppendUint(&w, c.TypeInt)
	case canoto__FieldType__TypeUint:
		Append(&w, canoto__FieldType__TypeUint__tag)
		AppendUint(&w, c.TypeUint)
	case canoto__FieldType__TypeFixedInt:
		Append(&w, canoto__FieldType__TypeFixedInt__tag)
		AppendUint(&w, c.TypeFixedInt)
	case canoto__FieldType__TypeFixedUint:
		Append(&w, canoto__FieldType__TypeFixedUint__tag)
		AppendUint(&w, c.TypeFixedUint)
	case canoto__FieldType__TypeBool:
		Append(&w, canoto__FieldType__TypeBool__tag)
		AppendBool(&w, true)
	case canoto__FieldType__TypeString:
		Append(&w, canoto__FieldType__TypeString__tag)
		AppendBool(&w, true)
	case canoto__FieldType__TypeBytes:
		Append(&w, canoto__FieldType__TypeBytes__tag)
		AppendBool(&w, true)
	case canoto__FieldType__TypeFixedBytes:
		Append(&w, canoto__FieldType__TypeFixedBytes__tag)
		AppendUint(&w, c.TypeFixedBytes)
	case canoto__FieldType__TypeRecursive:
		Append(&w, canoto__FieldType__TypeRecursive__tag)
		AppendUint(&w, c.TypeRecursive)
	case canoto__FieldType__TypeMessage:
		fieldSize := (c.TypeMessage).CachedCanotoSize()
		Append(&w, canoto__FieldType__TypeMessage__tag)
		AppendUint(&w, fieldSize)
		w = (c.TypeMessage).MarshalCanotoInto(w)
	}
	return w
}
